package doc

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	v "github.com/reliablyhq/cli/version"
)

func NewManCommand(rootCmd *cobra.Command) *cobra.Command {
	var outputDirectory string = "."

	cmd := &cobra.Command{
		Use:   "man",
		Args:  cobra.ExactArgs(0),
		Short: "Generates man pages for the reliably CLI.",
		Long:  "Generate one man page per command.",
		RunE: func(cmd *cobra.Command, args []string) error {
			header := doc.GenManHeader{
				Section: "1",
				// setting the Source forces removal of the 'auto generated by' message
				// for any command (ie even sub-commands) - in the man page footer -
				Source: fmt.Sprintf("Reliably %s", v.Version),
				Manual: "Reliably Manual",
			}
			return doc.GenManTree(rootCmd, &header, outputDirectory)
		},
	}

	cmd.Flags().StringVar(
		&outputDirectory,
		"output-dir",
		"",
		"Output directory of the generate man pages",
	)

	return cmd
}
