package cmd

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/MakeNowJust/heredoc/v2"
	fColor "github.com/fatih/color"

	//homedir "github.com/mitchellh/go-homedir"

	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/reliablyhq/cli/cmd/reliably/report"
	"github.com/reliablyhq/cli/core"
	"github.com/reliablyhq/cli/core/color"
	"github.com/reliablyhq/cli/core/config"
	ctx "github.com/reliablyhq/cli/core/context"
	"github.com/reliablyhq/cli/core/update"
	"github.com/reliablyhq/cli/utils"
	v "github.com/reliablyhq/cli/version"
)

// Choice is a list of string
type Choice []string

// Has indicates whether the string slice contains the value
func (list Choice) Has(a string) bool {
	return utils.StringInArray(a, list)
}

const (
	workspace = ".reliably"
)

var (
	verbose     bool
	version     = v.Version
	buildDate   = v.Date
	updaterRepo = "reliablyhq/cli"
)

func NewCmdRoot() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "reliably <command> [flags]",
		Short:             "Reliably CLI",
		Long:              `The Reliably Command Line Interface (CLI).`,
		Version:           version,
		SilenceErrors:     true, // quiet errors down stream
		SilenceUsage:      true, //silence usage when an error occurs
		DisableAutoGenTag: true, // disables auto gen tag "Auto generated by spf13/cobra..."
		//Example: heredoc.Doc(``),
		Annotations: map[string]string{
			"help:feedback": heredoc.Doc(`

Feedback:
  You can provide with feedback or report an issue at https://github.com/reliablyhq/cli/issues/new
`),
			"help:environment": heredoc.Doc(`

Environment variables:
  See 'reliably environment --help' for the list of supported environment variables.
`),
		},
	}

	cmd.PersistentFlags().BoolVarP(
		&verbose, "verbose", "v", false, "verbose output")
	// disable coloring directly in the dependency fatih/color package
	cmd.PersistentFlags().BoolVarP(
		&fColor.NoColor, "no-color", "", false, "Disable color output")
	cmd.SetVersionTemplate(FormatVersion(version, buildDate))
	cmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if err := setUpVerboseLogLevel(verbose); err != nil {
			return err
		}
		return nil
	}
	// help will not be indicated as command but only flag
	cmd.SetHelpCommand(&cobra.Command{
		Use:    "no-help",
		Hidden: true,
	})

	// Add commands
	cmd.AddCommand(NewCmdAuth())
	cmd.AddCommand(NewCmdDiscover()) // deprecated
	cmd.AddCommand(NewCmdCompletion())
	cmd.AddCommand(NewCmdVersion())
	cmd.AddCommand(NewCmdWorkflow())
	cmd.AddCommand(NewCmdHistory())
	cmd.AddCommand(NewCmdScan(cmd))

	cmd.AddCommand(report.NewCommand())

	//Help topics
	cmd.AddCommand(NewHelpTopic("environment"))

	// Uses a custom usage template - for adding feedback section to help -
	template := customUsageTemplate(cmd)
	cmd.SetUsageTemplate(template)

	return cmd
}

// Execute the root command and exit with nonzero code in case of errors
func Execute() {
	updateMessageChan := make(chan *update.ReleaseInfo)
	go func() {
		rel, _ := checkForUpdate(version)
		updateMessageChan <- rel
	}()

	if hostFromEnv := os.Getenv("RELIABLY_HOST"); hostFromEnv != "" {
		core.SetHostname(hostFromEnv)
	}

	rootCmd := NewCmdRoot()
	if err := rootCmd.Execute(); err != nil {
		er(err)
	}

	newRelease := <-updateMessageChan
	if newRelease != nil {
		color.Cyan()
		msg := fmt.Sprintf("%s %s → %s\n%s",
			color.Yellow("A new release of reliably is available:"),
			color.Cyan(version),
			color.Cyan(newRelease.Version),
			newRelease.URL)

		fmt.Fprintf(os.Stderr, "\n\n%s\n\n", msg)
	}
}

func init() {
	cobra.OnInitialize(initLogging)
	cobra.OnInitialize(initConfig)

}

/*
func init() {
	_ = createReliablyWorkspace()
}
*/

// initLogging ensure the log level is set depending on the verbose flag
func initLogging() {
	if err := setUpVerboseLogLevel(verbose); err != nil {
		er(err)
	}
}

// initConfig reads in config file.
func initConfig() {
	configHome := core.ConfigDir()
	configName := "config"
	configType := "yaml"
	configPath := filepath.Join(configHome, configName+"."+configType)

	// Create a new Viper global objec with custom options
	// - change the key delimiter to support dots in keys ie 'reliably.com'
	//   meaning the nested key lookup will be eg auths::reliably.com::token
	//viper.NewWithOptions(viper.KeyDelimiter("::"))

	config.Viper.AddConfigPath(configHome)
	config.Viper.SetConfigType(configType)
	config.Viper.SetConfigName(configName)

	// If a config file is found, read it in.
	if err := config.Viper.ReadInConfig(); err != nil {

		if _, ok := err.(viper.ConfigFileNotFoundError); ok {
			// Config file not found;
			// Ensure to create the config folder & file
			// Or Viper will not be able to write the file, if does not exist !
			err := os.MkdirAll(configHome, 0771)
			if err != nil {
				er(err)
			}
			if _, err := os.Create(configPath); err != nil {
				er(err)
			}
		} else {
			// Config file was found but another error was produced
			er(err)
		}
	} else {
		log.Debug(fmt.Sprintf("Using config file: %s", config.Viper.ConfigFileUsed()))
	}

	log.Debug(fmt.Sprintf("Loaded settings: %s", config.AllSettingsSecure()))
}

//set the log level to debug if verbose mode is on
func setUpVerboseLogLevel(verbose bool) error {

	if verbose {
		log.SetLevel(log.DebugLevel)
	} else {
		log.SetLevel(log.InfoLevel)
	}

	return nil
}

/*
func createReliablyWorkspace() error {
	//Create dir output using above code
	if _, err := os.Stat(workspace); os.IsNotExist(err) {
		log.Debug("Create workspace '.reliably'")
		err := os.Mkdir(workspace, 0755)
		if err != nil {
			return err
		}
	}

	// ensure policies cache is starting clean
	// so we remove before creating it
	// as removeAll removes path and any children it contains
	// NO_CACHE_CLEAN is an internal env var only for dev purpose
	policiesFolder := filepath.Join(workspace, "policies")
	if !(os.Getenv("NO_CACHE_CLEAN") != "" && v.IsDevVersion()) {
		os.RemoveAll(policiesFolder)
	}
	if _, err := os.Stat(policiesFolder); os.IsNotExist(err) {
		log.Debug(fmt.Sprintf("Create folder '%v'", policiesFolder))
		err := os.Mkdir(policiesFolder, 0755)
		if err != nil {
			return err
		}
	}

	return nil

}
*/

// CustomUsageTemplate returns usage template for the command.
// This is the default usage template from the command,
// with the additional help:feedback annotations, if specified
func customUsageTemplate(c *cobra.Command) string {

	tpl := c.UsageTemplate()

	if _, ok := c.Annotations["help:environment"]; ok {
		environment := c.Annotations["help:environment"]
		tpl = fmt.Sprintf("%s%s", tpl, environment)
	}

	if _, ok := c.Annotations["help:feedback"]; ok {
		feedback := c.Annotations["help:feedback"]
		tpl = fmt.Sprintf("%s%s", tpl, feedback)
	}

	cobra.AddTemplateFunc("StyleHeading", color.Yellow)
	replacer := strings.NewReplacer(
		`Usage:`, `{{StyleHeading "Usage:"}}`,
		`Aliases:`, `{{StyleHeading "Aliases:"}}`,
		`Examples:`, `{{StyleHeading "Examples:"}}`,
		`Available Commands:`, `{{StyleHeading "Available Commands:"}}`,
		`Global Flags:`, `{{StyleHeading "Global Flags:"}}`,
		// The following one steps on "Global Flags:"
		`Flags:`, `{{StyleHeading "Flags:"}}`,
		`Environment variables:`, `{{StyleHeading "Environment variables:"}}`,
		`Feedback:`, `{{StyleHeading "Feedback:"}}`,
		`Additional help topics:`, `{{StyleHeading "Additional help topics:"}}`,
	)
	tpl = replacer.Replace(tpl)

	return tpl
}

func shouldCheckForUpdate() bool {
	if os.Getenv("RELIABLY_NO_UPDATE_NOTIFIER") != "" {
		return false
	}

	return updaterRepo != "" && version != "DEV" &&
		!ctx.IsCI() && !isCompletionCommand() && utils.IsTerminal(os.Stderr)
}

func checkForUpdate(currentVersion string) (*update.ReleaseInfo, error) {
	if !shouldCheckForUpdate() {
		return nil, nil
	}

	repo := updaterRepo
	stateFilePath := path.Join(core.ConfigDir(), "release.yml")
	return update.CheckForUpdate(nil, stateFilePath, repo, currentVersion)
}

func isCompletionCommand() bool {
	return len(os.Args) > 1 && os.Args[1] == "completion"
}
