package cmd

import (
	"fmt"
	"os"
	"path"
	"runtime"
	"strings"

	surveyCore "github.com/AlecAivazis/survey/v2/core"
	"github.com/MakeNowJust/heredoc/v2"
	fColor "github.com/fatih/color"
	"github.com/mgutz/ansi"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"

	"github.com/reliablyhq/cli/api"
	"github.com/reliablyhq/cli/cmd/reliably/alpha"
	"github.com/reliablyhq/cli/cmd/reliably/beta"
	"github.com/reliablyhq/cli/cmd/reliably/cmdutil"
	"github.com/reliablyhq/cli/cmd/reliably/org"
	"github.com/reliablyhq/cli/cmd/reliably/slo"
	"github.com/reliablyhq/cli/config"
	"github.com/reliablyhq/cli/core/color"
	ctx "github.com/reliablyhq/cli/core/context"
	"github.com/reliablyhq/cli/core/update"
	"github.com/reliablyhq/cli/utils"
	v "github.com/reliablyhq/cli/version"
)

type Choice = cmdutil.Choice

var (
	verbose     bool
	noColor     bool
	version     = v.Version
	buildDate   = v.Date
	revision    = v.Revision
	updaterRepo = "reliablyhq/cli"
)

func NewCmdRoot() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "reliably <command> [flags]",
		Short:             "Reliably CLI",
		Long:              `The Reliably Command Line Interface (CLI).`,
		Version:           version,
		SilenceErrors:     true, // quiet errors down stream
		SilenceUsage:      true, //silence usage when an error occurs
		DisableAutoGenTag: true, // disables auto gen tag "Auto generated by spf13/cobra..."
		//Example: heredoc.Doc(``),
		Annotations: map[string]string{
			"help:feedback": heredoc.Doc(`

Feedback:
  You can provide with feedback or report an issue at https://github.com/reliablyhq/cli/issues/new
`),
			"help:environment": heredoc.Doc(`

Environment variables:
  See 'reliably environment --help' for the list of supported environment variables.
`),
		},
	}

	cmd.PersistentFlags().BoolVarP(
		&verbose, "verbose", "v", false, "verbose output")
	cmd.PersistentFlags().BoolVar(
		&noColor, "no-color", false, "Disable color output")
	cmd.SetVersionTemplate(FormatVersion(version, buildDate, revision))
	cmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		// This prerun hook is inherited by subcommands if not overridden
		// If this hook is needed by a subcommand, makes sure to excplicitely
		// call that root hook as:
		// cmd.Root().PersistentPreRunE(cmd, args)

		if err := setUpVerboseLogLevel(verbose); err != nil {
			return err
		}

		// any command should be run with authentication unless explicitly disabled
		doCheck := cmd != nil && cmd.Name() != "help" && cmdutil.IsAuthCheckEnabled(cmd)
		if doCheck && !cmdutil.CheckAuth() {
			cmdutil.PrintRequireAuthMsg()
			// force exit not to have colored error message,
			// as we handle more user-friendly message
			os.Exit(1)
		}

		return nil
	}
	cmd.Flags().Bool("help", false, "help for reliably")
	cmd.Flags().Bool("version", false, "version for reliably") // requires explicit or not shown with `reliably help`

	// Add commands
	cmd.AddCommand(NewCmdAuth())
	cmd.AddCommand(NewCmdDiscover()) // deprecated
	cmd.AddCommand(NewCmdCompletion())
	cmd.AddCommand(NewCmdVersion())
	cmd.AddCommand(NewCmdWorkflow())
	cmd.AddCommand(NewCmdHistory())
	cmd.AddCommand(NewCmdScan(cmd))
	cmd.AddCommand(NewCmdUpdate())
	cmd.AddCommand(org.NewCommand())
	cmd.AddCommand(slo.NewCommand())

	if v.IsDevVersion() {
		cmd.AddCommand(alpha.NewCommand())
		cmd.AddCommand(beta.NewCommand())
	}

	//Help topics
	cmd.AddCommand(NewHelpTopic("environment"))

	// disable auth chekc for root command itself
	cmdutil.DisableAuthCheck(cmd)

	noColor := strings.Contains(strings.Join(os.Args, " "), "--no-color")
	// force disabling coloring before we render the template or
	// help will always be colored even when flag is set - but not parsed yet -
	// because when using --help , persistent pre run is not yet executed
	if noColor || os.Getenv("NO_COLOR") != "" {
		disableColor()
	} else {
		customizeColor()
	}

	// Uses a custom usage template - for adding feedback section to help -
	template := cmdutil.CustomUsageTemplate(cmd)
	cmd.SetUsageTemplate(template)

	return cmd
}

// Execute the root command and exit with nonzero code in case of errors
func Execute() {
	updateMessageChan := make(chan *update.ReleaseInfo)
	go func() {
		rel, _ := checkForUpdate(version)
		updateMessageChan <- rel
	}()

	verbose = config.IsDebugMode()
	CheckOverriddenOrg()

	rootCmd := NewCmdRoot()
	if err := rootCmd.Execute(); err != nil {
		er(err)
	}

	newRelease := <-updateMessageChan
	if newRelease != nil {
		color.Cyan()
		upgradeCommand := getUpgradeCommand()
		msg := fmt.Sprintf("%s %s → %s\n\n%s\n%s%s",
			color.Yellow("A new release of reliably is available:"),
			color.Cyan(strings.TrimPrefix(version, "v")),
			color.Cyan(strings.TrimPrefix(newRelease.Version, "v")),
			color.Yellow("Details of the new release can be found here:"),
			newRelease.URL, upgradeCommand)

		fmt.Fprintf(os.Stderr, "\n\n%s\n\n", msg)
	}
}

func init() {
	cobra.OnInitialize(initLogging)
}

/*
func init() {
	_ = createReliablyWorkspace()
}
*/

// initLogging ensure the log level is set depending on the verbose flag
func initLogging() {
	if err := setUpVerboseLogLevel(verbose); err != nil {
		er(err)
	}
}

//set the log level to debug if verbose mode is on
func setUpVerboseLogLevel(verbose bool) error {
	if verbose {
		log.SetLevel(log.DebugLevel)
	} else {
		log.SetLevel(log.InfoLevel)
	}

	return nil
}

// disableColor disables coloring prompt & output for dependency libs
func disableColor() {
	surveyCore.DisableColor = true
	fColor.NoColor = true
}

// customizeColor changes a default color style for survey
// default answers will be non-bold light grey, instead of color too close
// to the question color style (question & default answer look very alike)
// -> override survey's color - code from GitHub CLI
// https://github.com/cli/cli/blob/ac0fe6bf715537a5fb9b99f80344ea098134a335/cmd/gh/main.go#L68
func customizeColor() {
	surveyCore.TemplateFuncsWithColor["color"] = func(style string) string {
		switch style {
		case "white":
			if color.Is256ColorSupported() {
				return fmt.Sprintf("\x1b[%d;5;%dm", 38, 242)
			}
			return ansi.ColorCode("default")
		default:
			return ansi.ColorCode(style)
		}
	}
}

func getUpgradeCommand() string {
	var message string
	switch runtime.GOOS {
	case "darwin", "linux", "windows":
		cmd := "$ reliably update"
		message = fmt.Sprintf("\n\n%s\n%s", color.Yellow("To upgrade on your system run:"), cmd)
	default:
		message = ""
	}

	return message
}

/*
func createReliablyWorkspace() error {
	//Create dir output using above code
	if _, err := os.Stat(workspace); os.IsNotExist(err) {
		log.Debug("Create workspace '.reliably'")
		err := os.Mkdir(workspace, 0755)
		if err != nil {
			return err
		}
	}

	// ensure policies cache is starting clean
	// so we remove before creating it
	// as removeAll removes path and any children it contains
	// NO_CACHE_CLEAN is an internal env var only for dev purpose
	policiesFolder := filepath.Join(workspace, "policies")
	if !(os.Getenv("NO_CACHE_CLEAN") != "" && v.IsDevVersion()) {
		os.RemoveAll(policiesFolder)
	}
	if _, err := os.Stat(policiesFolder); os.IsNotExist(err) {
		log.Debug(fmt.Sprintf("Create folder '%v'", policiesFolder))
		err := os.Mkdir(policiesFolder, 0755)
		if err != nil {
			return err
		}
	}

	return nil

}
*/

// CustomUsageTemplate returns usage template for the command.
// This is the default usage template from the command,
// with the additional help:feedback annotations, if specified
/*
func customUsageTemplate(c *cobra.Command) string {

	tpl := c.UsageTemplate()

	if _, ok := c.Annotations["help:environment"]; ok {
		environment := c.Annotations["help:environment"]
		tpl = fmt.Sprintf("%s%s", tpl, environment)
	}

	if _, ok := c.Annotations["help:feedback"]; ok {
		feedback := c.Annotations["help:feedback"]
		tpl = fmt.Sprintf("%s%s", tpl, feedback)
	}

	cobra.AddTemplateFunc("StyleHeading", color.Yellow)
	replacer := strings.NewReplacer(
		`Usage:`, `{{StyleHeading "Usage:"}}`,
		`Aliases:`, `{{StyleHeading "Aliases:"}}`,
		`Examples:`, `{{StyleHeading "Examples:"}}`,
		`Available Commands:`, `{{StyleHeading "Available Commands:"}}`,
		`Global Flags:`, `{{StyleHeading "Global Flags:"}}`,
		// The following one steps on "Global Flags:"
		`Flags:`, `{{StyleHeading "Flags:"}}`,
		`Environment variables:`, `{{StyleHeading "Environment variables:"}}`,
		`Feedback:`, `{{StyleHeading "Feedback:"}}`,
		`Additional help topics:`, `{{StyleHeading "Additional help topics:"}}`,
	)
	tpl = replacer.Replace(tpl)

	return tpl
}
*/

func shouldCheckForUpdate() bool {
	if os.Getenv("RELIABLY_NO_UPDATE_NOTIFIER") != "" {
		return false
	}

	return updaterRepo != "" && version != "DEV" &&
		!ctx.IsCI() && !isCompletionCommand() && !isUpdateCommand() &&
		utils.IsTerminal(os.Stderr)
}

func checkForUpdate(currentVersion string) (*update.ReleaseInfo, error) {
	if !shouldCheckForUpdate() {
		return nil, nil
	}

	repo := updaterRepo
	stateFilePath := path.Join(config.ConfigDir, "release.yml")
	return update.CheckForUpdate(nil, stateFilePath, repo, currentVersion)
}

func isCompletionCommand() bool {
	return len(os.Args) > 1 && os.Args[1] == "completion"
}

func isUpdateCommand() bool {
	return len(os.Args) > 1 && os.Args[1] == "update"
}

// CheckOverriddenOrg sets into the loaded config the org info (ID & name)
// from the overridden RELIABLY_ORG env var that accepts either an org UIUD
// or an org slug/name
func CheckOverriddenOrg() {

	if org := os.Getenv(config.RELIABLY_ORG); org != "" {

		var o *api.Organization
		var err error

		h := config.Hostname
		apiClient := api.NewClientFromHTTP(api.AuthHTTPClient(h))

		switch {
		case utils.IsValidUUID(org):
			o, err = api.GetOrganisation(apiClient, h, org)
		default:
			o, err = api.GetOrganizationByName(apiClient, h, org)
		}

		if err == nil {
			config.OverriddenOrg = &config.OrgInfo{
				ID:   o.ID,
				Name: o.Name,
			}
		}
		if err != nil {
			log.Debug(err)
		}

	}
}
