apiVersion: v1
kind: Objective
metadata:
  labels:
    name: api-availability
    service: example-api
spec:
  indicator_selector:
    provider: gcp
    category: availability
    gcp_project_id: abc123
    resource_id: myprojectid/google-cloud-load-balancers/myloadbalancer-name
  objective_percent: 99
  window: PT24H
---
apiVersion: v1
kind: Objective
metadata:
  labels:
    name: api-latency
    service: example-api
spec:
  indicator_selector:
    provider: gcp
    category: latency
    gcp_project_id: abc123
    resource_id: myprojectid/google-cloud-load-balancers/myloadbalancer-name
    threshold: 100ms
  objective_percent: 99
  window: PT24H