apiVersion: reliably.com/v1
kind: Objective
metadata:
  labels:
    name: api-availability
    service: reliably-api
spec:
  indicatorSelector:
    category: availability
    gcp_loadbalancer_name: example-lb
    gcp_project_id: example-id
  objectivePercent: 99
  window: 1h0m0s
---
apiVersion: reliably.com/v1
kind: Objective
metadata:
  labels:
    name: api-latency
    service: reliably-api
spec:
  indicatorSelector:
    category: latency
    gcp_loadbalancer_name: example-lb
    gcp_project_id: example-id
    latency_target: 300ms
    percentile: "99"
  objectivePercent: 99
  window: 24h0m0s