name: Reliably CLI Release

on:
  push:
    tags:
      - "*.*.*"
  release:
    types: [published]

jobs:
  checks:
    uses: ./.github/workflows/cli-check.yaml
  publish-wheels:
    name: Publish wheels
    runs-on: ubuntu-22.04
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
      - name: Publish wheels
        run: |
          pdm publish

          # try to give Pypi time to update its index. Unfortunate.
          sleep 60s
        env:
          PDM_PUBLISH_USERNAME: __token__
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  build-container:
    name: Build containers
    runs-on: ubuntu-22.04
    needs:
      - publish-wheels
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: meta for the container image
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            prefix=
          images: |
            ghcr.io/reliablyhq/cli/cli
          tags: |
            type=sha,prefix=,format=long
            type=raw,value=latest
      - name: Build and push Container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
