name: Reliably CLI Release

on:
  push:
    branches:
      - main
    tags:
      - "cli-v*.*.*"

jobs:
  checks:
    uses: ./.github/workflows/cli-check.yaml
  build-container:
    runs-on: ubuntu-22.04
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile
          tags: |
            ghcr.io/reliablyhq/cli:latest
  build-wheels:
    name: Build wheels
    runs-on: ubuntu-22.04
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.10"
      - name: Build wheel
        run: |
          pdm build --no-sdist
