name: Reliably CLI Lint/Test

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pdm sync -d

      - name: Run Lint
        run: |
          pdm run lint

      - name: Run Tests
        run: |
          pdm run pytest
