name: Integration Tests

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'v*' # We don't want this to run on release
  workflow_dispatch:

jobs:
  cli-to-api:
    runs-on: ubuntu-latest
    env:
      GCP_CA_RULE_PRIORITY: ${{ secrets.GCP_CA_RULE_PRIORITY }}
      CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT }}
      RELIABLY_HOST: ${{ secrets.RELIABLY_HOST }}
      RELIABLY_TOKEN: ${{ secrets.RELIABLY_TOKEN }}
    steps:
      ### Workflow setup
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Authenticate with Gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Ensure GH rule does not exist yet
        run: |
          gcloud compute security-policies rules delete $GCP_CA_RULE_PRIORITY \
          --security-policy deny-all-to-staging --quiet
        continue-on-error: true
      - name: Whitelist public IP to Cloud Armor
        run: |
          gcloud compute security-policies rules create $GCP_CA_RULE_PRIORITY \
            --security-policy deny-all-to-staging \
            --src-ip-ranges "${{ steps.ip.outputs.ipv4 }}" \
            --action allow --description "Whitelist GitHub Workflow"
      - run: sleep 60 # sleep is required to have the firewall being operational - it takes some time to whitelist -

      ### Build the CLI
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Download Go dependencies
        run: go mod download
      - name: Build the CLI
        run: go build -o bin/reliably main.go

      ### Tests some CLI commands with API usage in backend
      - name: Check CLI is authenticated to API
        run: ./bin/reliably auth status
      - name: Run simple demo scan
        run: ./bin/reliably scan .
        continue-on-error: true

      ### Workflow teardown
      - name: Removes public IP from Cloud Armor Whitelist (failure)
        if: failure()
        # exit 1 - to fail the entire workflow in case a previous step failed - but ensure to remove the policy
        run: |
          gcloud compute security-policies rules delete $GCP_CA_RULE_PRIORITY \
          --security-policy deny-all-to-staging --quiet
          exit 1
      - name: Removes public IP from Cloud Armor Whitelist
        if: success()  # does not fail the workflow
        run: |
          gcloud compute security-policies rules delete $GCP_CA_RULE_PRIORITY \
          --security-policy deny-all-to-staging --quiet
