name: Trigger a new release [Manual]

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release. It must start with a 'v' prefix and follow semver eg 'v1.2.3'."
        required: true

jobs:
  draft-new-release:
    name: "Trigger a new release"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}
      # In order to make a commit, we need to initialize the delivery user.
      - name: Initialize mandatory git config
        run: |
          git config user.email "74009226+reliably-ci@users.noreply.github.com"
          git config user.name "CI at Reliably"
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md
          git commit -s --message "Prepare release ${{ github.event.inputs.version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin release/${{ github.event.inputs.version }}
      - name: Create pull request by Reliably-CI user
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release version ${{ github.event.inputs.version }}
          # reviewers: ${{ github.actor }} # We do not set explicit reviewer as it will be automatically approved by GH-actions bot
          body: |
            This PR was created in response to a manual trigger by @${{ github.actor }} of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog in this commit: ${{ steps.make-commit.outputs.commit }}.
            This PR will be automatically merged by @github-actions bot.
            Then a new tag on main branch will be pushed to trigger the release of the CLI.
      - run: sleep 30 # GH is lately taking some time to validate DCO failing the workflow (leaving the PR unmerged)
      - name: Find pull request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: release/${{ github.event.inputs.version }}
      - name: Automatically approve pull request by worklow user
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # beware the manual user here !! approver must be different that creator of the PR
          number: ${{ steps.find-pull-request.outputs.number }}
      - name: Merge pull request by Reliably-CI user
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_PAT }}
          number: ${{ steps.find-pull-request.outputs.number }}
          method: rebase
      - name: Delete release branch
        run: |
          git push origin --delete release/${{ github.event.inputs.version }}
        continue-on-error: true # release branch might be deleted upon PR merge
      - name: Create the git tag (trigger release build)
        run: |
          git checkout main
          git pull
          git tag ${{ github.event.inputs.version }}
          git log --name-status HEAD^..HEAD
          git push --tags
